### PR TITLE
Various fixes to build system

### PR DESCRIPTION
**Pull request by cholmcc**
- Use system libyaml-cpp if available and of suitable version.
  Otherwise, build own.  The built one should probably be
  statically linked in to the library - not a separate shared
  library.
- Install headers from Cuba and einhard as they are needed by
  SMASH headers
- Install example input files to prefix/share/smash
- Remove explicit `std=c++11` flag in CMAKE_CXX_FLAGS` that can cause problems with external builds and links 
Pertaints to #15

### CODE REVIEW

**Comment by doliinychenko** [comment]
SMASH was already usable as a callable library at some point, see smash/examples/using_SMASH_as_library folder, and the suggested changes are mostly a comfort improvement and cleanup. Which is great! Thanks! As far as I understand, the changes are mainly intended to enable the 
```
make install
```
for SMASH. The `make install` copies binaries and library to the right places so compilers know where to look for them. It's going to be a bit more challenging on a cluster, where you only can access home folder. Then it should be something like
```
make install --prefix ~/.local/
```
I would suggest to update INSTALL file to reflect this.

**Review by doliinychenko — APPROVED** [review]

**Comment by stdnmr** [comment]
I agree with @doliinychenko here, it would be great if a small section at the end of the `## How to Build SMASH` section in the `README.md` file, maybe titled `### Installing SMASH`, could be added.

@cholmcc maybe you could help with a short formulation for the documentation what `make install` now does. Either posting it here (and I add it later) or you can also directly adding it to the `README.md` and commit it here. I will then merge after 

Thanks for your contributions, we really appreciate the external help.

**Comment by cholmcc** [comment]
Hi both, 

Here is already a standard way of setting the installation prefix with **CMake** - just define `CMAKE_INSTALL_PREFIX` 

    cmake -DCMAKE_INSTALL_PREFIX=${HOME}/.local  ...
    make install

(note, `~/.local` for user installed software - parallel to `/usr/local` - is something of a common practie - that is for example how `pip` works).   The default installation target is `/usr/local` 

In any case: 

> # Installation 
>
> Installation of SMASH can be done with 
>
>     make install 
>
> If you want to install somewhere other than `/usr/local` configure the source tree and set `CMAKE_INSTALL_PREFIX` to your desired location (see also [CMake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html).  For example, if you want to install in `${HOME}/.local`, do 
>
>     cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local ...
>     make install 
>
> Binaries will end up in `CMAKE_INSTALL_PREFIX/bin`, libraries in `CMAKE_INSTALL_PREFIX/lib`, headers in `CMAKE_INSTALL_PREFIX/include/smash`, and data in `CMAKE_INSTALL_PREFIX/share/smash`. 
>
> # Building out of source tree 
>
> A good practise is to build binary code outside of the source tree.  Fortunately, the build system of SMASH ([CMake](https://cmake.org) allows for that).  The philisophy is "do not eat where you ..." - well you get it.  Suppose you had the SMASH sources in `src`, 
> 
>     $ ls
>     src 
>
> then make a directory next to it called say `build` and go there 
>
>     $ mkdir build
>     $ cd build 
>
> Now configure the source tree with `cmake` pointing to the source directory 
>
>     $ cmake ../src ...
>
> Now you can build (and install) as per usual.

**Comment by cholmcc** [comment]
@doliinychenko I know the example in `examples/using_SMASH_as_library`, which is fine for the stuff listed there.  But to run SMASH as an event generator like many experiments do to make comparisons etc. more is needed.  See also recent PRs #19 and #20

**Comment by stdnmr** [comment]
While testing the branch before merging it, I noticed two issues:

1. In our root `CMakeLists.txt` we check that C++11 code compiles. This errors if the `-std=c++11` is removed. Maybe we need to follow your idea from #15 and define a variable `CMAKE_CXX_STANDARD_VERSION` after all.
2. We use the `DCMAKE_INSTALL_PREFIX` to find the eigen headers, if there were not installed, which seems a bit odd to me now. Anyway, if one follows the instruction in the `README.md` to include the eigen headers ("in `smash/build/`, create build files with `cmake -DCMAKE_INSTALL_PREFIX=$HOME/[latest-eigen]/ ..`") `make install` will end up installing everything into `$HOME/[latest-eigen]/`, which is of course not what one wants. My two solutions would be two either change the include the eigen headers section (eigen ships with its one `make install` that should make them findable by cmake) or at least at this potential conflict as a note to the new `### Installation` section. I can take care of this one, maybe after a feedback, what is the better solution.

I also found some minor formatting issues that I will fix directly before merging to master.

**Comment by cholmcc** [comment]
Just to be clear:

[`CMAKE_INSTALL_PREFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) is the _expected_ variable to set to define an installation target.  It is _not_ meant to be the place to look for specific headers (as I think you also indicate).   The _de facto_ standard seems to be to look for header, libraries, etc. from package _X_ under `${`_X_`PATH}` - e.g., to look for _HepMC3_ under `${HEPMC3_PATH}`.  So for you, you should look for the _Eigen_ headers under ${`EIGEN_PATH}/include` _in addition_ to looking in standard places (`/usr/include`, `/usr/local/include`, `C:\Program Files\eigen\include`, and so on).  One _can_ also look in `${CMAKE_INSTALL_PREFIX}/include` as a last resort. 

Wrt C++11 - if you want to ensure that the target compiler understands C++11, then test that assumption with a test in `CMakeLists.txt`.  If you want to pass a specific option to the compiler, you should test if the compiler understands that option with [`check_cxx_compiler_flag`](https://cmake.org/cmake/help/latest/module/CheckCXXCompilerFlag.html) (from `include(CheckCXXCompilerFlag)`).  But _do not_ set explicitly a particular standards version - third-party users may want to link with code that is compiled with a more recent version - say C++20 - where ABI compatibility may be a problem.  You should check out [`CXX_STANDARD`](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html) and related. 

Yours,

Christian

**Comment by cholmcc** [comment]
BTW, I believe you can add commits on the PR branch.

**Comment by stdnmr** [comment]
> [`CMAKE_INSTALL_PREFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) is the _expected_ variable to set to define an installation target. It is _not_ meant to be the place to look for specific headers (as I think you also indicate). The _de facto_ standard seems to be to look for header, libraries, etc. from package _X_ under `${`_X_`PATH}` - e.g., to look for _HepMC3_ under `${HEPMC3_PATH}`. So for you, you should look for the _Eigen_ headers under ${`EIGEN_PATH}/include` _in addition_ to looking in standard places (`/usr/include`, `/usr/local/include`, `C:\Program Files\eigen\include`, and so on). One _can_ also look in `${CMAKE_INSTALL_PREFIX}/include` as a last resort.

Yes, that is what I thought, I will change our build instructions accordingly.

> Wrt C++11 - if you want to ensure that the target compiler understands C++11, then test that assumption with a test in `CMakeLists.txt`. If you want to pass a specific option to the compiler, you should test if the compiler understands that option with [`check_cxx_compiler_flag`](https://cmake.org/cmake/help/latest/module/CheckCXXCompilerFlag.html) (from `include(CheckCXXCompilerFlag)`). But _do not_ set explicitly a particular standards version - third-party users may want to link with code that is compiled with a more recent version - say C++20 - where ABI compatibility may be a problem. You should check out [`CXX_STANDARD`](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html) and related.

I see. Thanks for the explanations. We will make changes accordingly here, too.

**Comment by stdnmr** [comment]
> BTW, I believe you can add commits on the PR branch.

Yes, this works now thanks.

**Comment by stdnmr** [comment]
Fixed the two issues i noticed with 63e6d93 and aebe4f8. Now I only see some warning with the install commands on the cluster like

```
....
install DIRECTORY given no DESTINATION!
...
install FILES given no DESTINATION!
...
```
Probably easy to fix. I will take care of them next week, then this is ready to merge.

**Comment by stdnmr** [comment]
Fixed the last problem the `TYPE` option of install (although nice) requires newer version of CMake that we do not have to available everywhere, where SMASH needs to run. Merging.

**Pull request merged**
